#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/pocket_cube.py /autograder/source/pocket_cube.py
cp /autograder/submission/pocket_cube_solver.py /autograder/source/pocket_cube_solver.py

cd /autograder/source

python3 run_tests.py
