import random
import time
#This file contains Python implementations of the sorting algorithms that we have studied.
#   BubbleSort
#   SelectionSort
#   InsertionSort
#   MergeSort
#   QuickSort
#Some functions copied from https://www.geeksforgeeks.org/comparison-among-bubble-sort-selection-sort-and-insertion-sort/
#These functions are described in the notes. 
#The purpose of this document is to collect the code in one place, 
#   and to remove the print statements so that the code itself is easier to read.

def bubble_sort(arr: list[int]) -> None:
    n = len(arr)
    for i in range(n):
        for j in range(n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]

def selection_sort(arr: list[int]) -> None:
    n = len(arr)
    for i in range(n):
        min_index = i
        for j in range(i + 1, n):
            if arr[j] < arr[min_index]:
                min_index = j
        arr[i], arr[min_index] = arr[min_index], arr[i]

def insertion_sort(arr: list[int])-> None:
    n = len(arr)
    for i in range(1, n):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

def merge_step(list1: list[int], 
               list2: list[int]) -> list[int]:
    '''
    Input:assumes list1 and list2 are sorted lists of integers
    Output: the list (list1+list2).sort()'''
    new_list=[]
    while(len(list1)>0 and len(list2)>0):
        #Iteratively move the smaller of the smallest to the new list until one list is empty.
        smallest_of_list1 = list1[0]
        smallest_of_list2 = list2[0]
        if smallest_of_list1<smallest_of_list2:
            list1=list1[1:] #Removes the first item of list1
            new_list.append(smallest_of_list1) #Puts that first item on new_list.
        else:
            list2 = list2[1:]
            new_list.append(smallest_of_list2)
    #At this point, at least one of list1 or list2 is empty. 
    #Put the remaining part of the nonempty list on the end of new_list.
    if len(list1)==0:
        new_list.extend(list2)
    elif len(list2)==0:
        new_list.extend(list1)
    return new_list

def mergesort(list_to_sort: list[int]) -> list[int]:
    '''
    A divide-and-conquer method for sorting.
    Input: lists_to_sort is a list of integers. 
        quiet_mode is a flag that determines whether partial outputs will be printed.
        id is an integer that identifies this run of mergesort.
        parent is an integer that identifies the run of mergesort that called the current one.
    Output: a sorted version of list_to_sort
    Side-Effects: None
    '''
    if len(list_to_sort)<=1: #Base case.
        return list_to_sort
    #The divide step:
    middle = len(list_to_sort)//2 
    list1 = list_to_sort[:middle] 
    list2 = list_to_sort[middle:] 
    #Conquer, recursively:
    list1 = mergesort(list1)
    list2 = mergesort(list2)
    #Complete conquering at this step by calling merge_step to combine the sorted lists, list1 and list2
    return merge_step(list1,list2)
def quicksort(arr: list[int]) -> list[int]: #Code generated by ChatGPT3.5
    '''
    Input: arr is an unsorted list.
    Output: a sorted list.
    Side-Effects: None.
    Repeatedly selects a 'pivot' element. 
        Creates a new list with all elements less than the pivot to its left 
                            and elements greater than the pivot to its right.
        Then recurse on both the left and right parts of the list.
    '''
    
    if len(arr) <= 1:
        return arr
    pivot_index = len(arr) // 2
    pivot = arr[pivot_index] #Chooses the pivot to be in the middle.
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return (quicksort(left)       
            + middle 
            + quicksort(right) #Makes two recursive calls.
    )


#---Timing the basic sorting algorithms---#

# Generate a list of 10000 random integers
arr = [random.randint(1, 10000) for i in range(10000)]
print("sorted", quicksort(arr))

# Sort the list using each algorithm and time it
start_time = time.time()
bubble_sort(arr.copy())
bubble_sort_time = time.time() - start_time

start_time = time.time()
selection_sort(arr.copy())
selection_sort_time = time.time() - start_time

start_time = time.time()
insertion_sort(arr.copy())
insertion_sort_time = time.time() - start_time

print("Bubble Sort time:", bubble_sort_time)
print("Selection Sort time:", selection_sort_time)
print("Insertion Sort time:", insertion_sort_time)
