#!/usr/bin/env bash

# Set up autograder files

cp /autograder/submission/pocket_cube_solver_solution.py /autograder/source/pocket_cube_solver_solution.py

cd /autograder/source

python3 run_tests.py
