from unittest import TestCase
from pocket_cube_solver import *
import unittest
from utils.timeout import timeout
from gradescope_utils.autograder_utils.decorators import weight, visibility, number

class TestsOfStarterCode(TestCase):
    def test_rotations(self):
        #Check that each rotation has order 4.
        #This is a basic assurance that the move permutations were written correctly.
        P = pocket_cube()
        Q = pocket_cube()
        for mv in pocket_cube.move_permutation_dict:
            for i in range(4):
                P.perform_move(mv,mutate=True)
            assert P==Q 
    def test_scramble_unscramble(self):
        #Check that scrambling, then performing the reverse moves unscrambles the cube.
        #This is a basic assurance that move sequences are being inverted correctly.
        P=pocket_cube()
        scramble_sequence = P.scramble()
        assert not P.state == list(range(24)) #This may occasionally fail if we scramble back to identity. But this is rare.
        unscramble_sequence= pocket_cube.invert_move_sequence(scramble_sequence)
        P.perform_move_sequence(unscramble_sequence)
        assert P.state == list(range(24))

    def test_twist_invariant(self):
        #Checks that the total twist is always 0.
        P=pocket_cube()
        for mv in pocket_cube.move_cost_dict:
            Q = P.perform_move(mv)
            total_twist = 0
            for cubie in itertools.product([0,1],repeat = 3):
                total_twist += Q.get_twist_of_cubie(cubie)
            assert total_twist%3==0

class TestsOfStudentCode(TestCase):
    small_scrambles = [['F'],['U2'],['F','B'],['Bp','U','R2','Dp','L'], ['R','L','U','R','D'],['Dp','Up','R','B2','Lp']]
    large_scrambles = [['D', 'U', 'D', 'Rp', 'Rp', 'F', 'U', 'B', 'F', 'Dp', 'Up', 'R', 'Rp', 'L2', 'B', 'L2', 'F', 'U', 'R', 'Bp', 'U', 'B', 'Bp', 'Fp', 'L', 'U', 'R', 'Fp', 'L2', 'D'], 
                       ['Fp', 'F2', 'R2', 'L2', 'Lp', 'Up', 'Lp', 'Up', 'Fp', 'U', 'D2', 'B', 'U', 'L', 'R', 'Fp', 'R', 'R', 'L', 'R', 'D2', 'F', 'U', 'L2', 'B', 'Dp', 'B2', 'D', 'U', 'D'], 
                       ['B', 'Up', 'Fp', 'D2', 'U2', 'D2', 'R', 'Dp', 'Dp', 'U', 'D', 'U', 'Rp', 'L2', 'Lp', 'Lp', 'F', 'D', 'U2', 'R2', 'Dp', 'B2', 'Bp', 'Bp', 'F', 'Dp', 'U2', 'U2', 'U2', 'Lp'], 
                       ['Lp', 'F', 'L', 'D2', 'B', 'L2', 'Lp', 'L', 'R2', 'F', 'U', 'R', 'Bp', 'D2', 'R2', 'F', 'B', 'L2', 'L2', 'B2', 'D', 'Rp', 'B', 'Lp', 'B2', 'R', 'Lp', 'F2', 'L', 'F2'], 
                       ['Up', 'U2', 'U', 'Rp', 'Rp', 'U2', 'Lp', 'F2', 'Lp', 'U', 'R2', 'Dp', 'R', 'Dp', 'R2', 'Rp', 'Up', 'U2', 'U', 'B', 'L', 'Lp', 'L', 'B', 'L', 'B', 'B2', 'R2', 'Lp', 'L2'], 
                       ['U', 'R2', 'D', 'U2', 'Lp', 'F', 'F', 'Fp', 'Rp', 'L2', 'R', 'F', 'B', 'D2', 'D', 'R2', 'Dp', 'R', 'Up', 'F2', 'R', 'U', 'L2', 'Dp', 'L2', 'R', 'Up', 'Dp', 'D2', 'B2'], 
                       ['R', 'F2', 'F', 'Fp', 'Bp', 'D2', 'D2', 'D2', 'L', 'Dp', 'Lp', 'F', 'D', 'L', 'Rp', 'F', 'U2', 'U2', 'Fp', 'B', 'F2', 'B', 'F', 'L', 'Bp', 'Dp', 'U', 'Lp', 'Dp', 'D2']]

    @weight(15)
    @timeout(5*245*1.2)
    #This time was generated by sampling 10 random samples and timing to solve them. 245 was the max time, 64 was the average time.
    #I removed the scramble that took the longest time and 4 others to get 5 long scrambles.
    #With an additional 20% time on top of this, you should be able to solve all 5 scrambles in this amount of time.
    #Don't submit to gradescope until this test passes locally. Let me know if the test passes locally but not on gradescope.
    def test_general_solution(self):
        for scramble_seq in type(self).large_scrambles:
            scrambled_cube = pocket_cube()
            scrambled_cube.perform_move_sequence(scramble_seq) #scramble the cube.
            assert not scrambled_cube == pocket_cube() #check that the cube is scrambled.
            solve_sequence = solve_cube(scrambled_cube) #use your method find a solution
            scrambled_cube.perform_move_sequence(solve_sequence) #perform your solution.
            assert scrambled_cube==pocket_cube() #check that the cube is solved.

if __name__=="__main__":
    #T = TestsOfStudentCode()
    #T.test_small_scramble_dijkstra()
    unittest.main()
